# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d10f759983926f5a2759e6ea57f99c08a687ce3709576940dc8875f44175d6a68643a5f1bf7231e72befa8b9e750c3075ce4d3217f3b1278dc4ff28a129283b8
  cloud_name: <%= ENV["PETSITTER_CLOUDINARY_CLOUD_NAME"] %>
  api_key: <%= ENV["PETSITTER_CLOUDINARY_API_KEY"] %>
  api_secret: <%= ENV["PETSITTER_CLOUDINARY_API_SECRET"] %>
  enhance_image_tag: true
  static_image_support: true
test:
  secret_key_base: 1e3ad3cfe02f8da338602360bff29c39ec5a8dac31d3c368dcc356a5224de213ae78b6adabee826a739ab6f6a57f68846fea0a112c8d492076a254a553464640
  cloud_name: <%= ENV["PETSITTER_CLOUDINARY_CLOUD_NAME"] %>
  api_key: <%= ENV["PETSITTER_CLOUDINARY_API_KEY"] %>
  api_secret: <%= ENV["PETSITTER_CLOUDINARY_API_SECRET"] %>
  enhance_image_tag: true
  static_image_support: true
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  cloud_name: <%= ENV["PETSITTER_CLOUDINARY_CLOUD_NAME"] %>
  api_key: <%= ENV["PETSITTER_CLOUDINARY_API_KEY"] %>
  api_secret: <%= ENV["PETSITTER_CLOUDINARY_API_SECRET"] %>
  enhance_image_tag: true
  static_image_support: true
